/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    Pet: typeof import('./src/components/Pet/Pet.vue')['default']
    SpriteAnimator: typeof import('./src/components/SpriteAnimator/SpriteAnimator.vue')['default']
  }
}
